// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/olc1_vj24_3363565520917/backend/analisis/lexico.jflex


package olc1_vj24_3363565520917.backend.analisis;

//importaciones
import java_cup.runtime.Symbol;
import java.util.LinkedList;
import olc1_vj24_3363565520917.backend.excepciones.Errores;


@SuppressWarnings("fallthrough")
public class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  3,  4,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  5,  6,  0,  0,  7,  8,  9, 10, 11, 12, 13,  0, 14, 15, 16, 
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 18, 19, 20, 21, 22,  0, 
     0, 23, 24, 25, 26, 27, 28, 29, 30, 31,  0, 32, 33, 34, 35, 36, 
    37,  0, 38, 39, 40, 41, 42, 43,  0,  0,  0,  0,  0,  0, 44, 45, 
     0, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 
    61, 55, 62, 63, 64, 65, 66, 67, 55, 55, 55, 68, 69, 70,  0,  0, 
     0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\1\1\4\2\1\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\14\1\1\21\1\22\15\23\1\24"+
    "\1\1\1\25\1\26\1\0\1\27\1\30\1\0\1\31"+
    "\1\32\1\33\1\0\1\2\1\0\1\34\1\35\1\36"+
    "\4\0\1\37\3\0\1\40\7\0\4\23\1\37\3\23"+
    "\1\40\7\23\1\41\1\42\1\0\1\43\7\0\1\44"+
    "\1\45\4\0\1\46\1\0\7\23\1\44\1\45\4\23"+
    "\1\46\1\23\1\2\1\47\1\0\1\50\3\0\1\51"+
    "\3\0\1\52\1\0\1\47\1\23\1\50\3\23\1\51"+
    "\3\23\1\52\1\23\1\53\2\0\1\54\2\0\1\55"+
    "\1\53\2\23\1\54\2\23\1\55\1\0\1\56\1\0"+
    "\1\57\1\23\1\56\1\23\1\57\1\0\1\60\1\23"+
    "\1\60\2\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\107\0\216\0\325\0\u011c\0\107\0\u0163\0\u01aa"+
    "\0\107\0\107\0\u01f1\0\u0238\0\u027f\0\u02c6\0\u030d\0\107"+
    "\0\107\0\u0354\0\u039b\0\u03e2\0\u0429\0\u0470\0\u04b7\0\u04fe"+
    "\0\u0545\0\u058c\0\u05d3\0\u061a\0\u0661\0\u06a8\0\u06ef\0\u0736"+
    "\0\107\0\107\0\u077d\0\u07c4\0\u080b\0\u0852\0\u0899\0\u08e0"+
    "\0\u0927\0\u096e\0\u09b5\0\u09fc\0\u0a43\0\u0a8a\0\u0ad1\0\107"+
    "\0\u0b18\0\107\0\107\0\u011c\0\107\0\107\0\u0b5f\0\107"+
    "\0\107\0\107\0\u0ba6\0\u0bed\0\u0c34\0\107\0\107\0\107"+
    "\0\u0c7b\0\u0cc2\0\u0d09\0\u0d50\0\u0d97\0\u0dde\0\u0e25\0\u0e6c"+
    "\0\107\0\u0eb3\0\u0efa\0\u0f41\0\u0f88\0\u0fcf\0\u1016\0\u105d"+
    "\0\u10a4\0\u10eb\0\u1132\0\u1179\0\u11c0\0\u1207\0\u124e\0\u1295"+
    "\0\u077d\0\u12dc\0\u1323\0\u136a\0\u13b1\0\u13f8\0\u143f\0\u1486"+
    "\0\107\0\107\0\u14cd\0\u0c34\0\u1514\0\u155b\0\u15a2\0\u15e9"+
    "\0\u1630\0\u1677\0\u16be\0\107\0\107\0\u1705\0\u174c\0\u1793"+
    "\0\u17da\0\107\0\u1821\0\u1868\0\u18af\0\u18f6\0\u193d\0\u1984"+
    "\0\u19cb\0\u1a12\0\u077d\0\u077d\0\u1a59\0\u1aa0\0\u1ae7\0\u1b2e"+
    "\0\u077d\0\u1b75\0\u0ba6\0\107\0\u1bbc\0\107\0\u1c03\0\u1c4a"+
    "\0\u1c91\0\107\0\u1cd8\0\u1d1f\0\u1d66\0\107\0\u1dad\0\u077d"+
    "\0\u1df4\0\u077d\0\u1e3b\0\u1e82\0\u1ec9\0\u077d\0\u1f10\0\u1f57"+
    "\0\u1f9e\0\u077d\0\u1fe5\0\107\0\u202c\0\u2073\0\107\0\u20ba"+
    "\0\u2101\0\107\0\u077d\0\u2148\0\u218f\0\u077d\0\u21d6\0\u221d"+
    "\0\u077d\0\u2264\0\107\0\u22ab\0\107\0\u22f2\0\u077d\0\u2339"+
    "\0\u077d\0\u2380\0\107\0\u23c7\0\u077d\0\107\0\u077d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\2\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\2\1\25"+
    "\1\26\1\27\1\30\1\31\2\2\1\32\2\2\1\33"+
    "\2\2\1\34\1\2\1\35\1\36\1\2\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\2\43\1\51\3\43\1\52\2\43\1\53\1\43\1\54"+
    "\1\55\1\43\1\56\1\57\1\60\1\61\1\62\110\0"+
    "\2\3\1\0\1\3\127\0\1\63\61\0\6\64\1\65"+
    "\100\64\10\0\1\66\76\0\11\67\1\0\75\67\14\0"+
    "\1\70\107\0\1\71\107\0\1\72\104\0\1\73\3\0"+
    "\1\74\105\0\1\75\1\0\1\17\112\0\1\76\106\0"+
    "\1\77\106\0\1\100\125\0\1\101\1\0\1\102\25\0"+
    "\1\101\1\0\1\102\46\0\1\103\5\0\1\104\20\0"+
    "\1\103\6\0\1\104\56\0\1\105\27\0\1\105\53\0"+
    "\1\106\27\0\1\106\44\0\1\107\14\0\1\110\11\0"+
    "\1\107\15\0\1\110\46\0\1\111\6\0\1\112\17\0"+
    "\1\111\7\0\1\112\42\0\1\113\26\0\1\113\76\0"+
    "\1\114\27\0\1\114\60\0\1\115\27\0\1\115\54\0"+
    "\1\116\27\0\1\116\37\0\1\117\26\0\1\117\66\0"+
    "\1\120\26\0\1\120\77\0\26\43\47\0\1\101\1\0"+
    "\1\102\7\0\16\43\1\121\1\43\1\122\5\43\41\0"+
    "\1\103\5\0\1\104\11\0\7\43\1\123\6\43\1\124"+
    "\7\43\47\0\1\105\11\0\16\43\1\125\7\43\44\0"+
    "\1\106\14\0\13\43\1\126\12\43\32\0\1\107\14\0"+
    "\1\110\11\0\1\127\15\43\1\130\7\43\37\0\1\111"+
    "\6\0\1\112\12\0\5\43\1\131\7\43\1\132\10\43"+
    "\32\0\1\113\26\0\1\133\25\43\51\0\1\114\7\0"+
    "\20\43\1\134\5\43\53\0\1\115\5\0\22\43\1\135"+
    "\3\43\51\0\1\116\7\0\20\43\1\136\5\43\32\0"+
    "\1\117\26\0\1\137\25\43\41\0\1\120\17\0\7\43"+
    "\1\140\16\43\110\0\1\141\12\0\1\142\75\0\3\73"+
    "\2\0\7\73\1\143\72\73\2\74\1\0\104\74\21\0"+
    "\1\144\131\0\1\145\27\0\1\145\45\0\1\146\26\0"+
    "\1\146\53\0\1\147\26\0\1\147\73\0\1\150\27\0"+
    "\1\150\64\0\1\151\27\0\1\151\54\0\1\152\27\0"+
    "\1\152\50\0\1\153\27\0\1\153\63\0\1\154\27\0"+
    "\1\154\60\0\1\155\27\0\1\155\56\0\1\156\27\0"+
    "\1\156\45\0\1\157\26\0\1\157\66\0\1\160\27\0"+
    "\1\160\61\0\1\161\27\0\1\161\53\0\1\162\27\0"+
    "\1\162\47\0\1\163\26\0\1\163\64\0\1\145\11\0"+
    "\16\43\1\164\7\43\36\0\1\146\22\0\4\43\1\165"+
    "\21\43\32\0\1\147\26\0\1\166\25\43\46\0\1\150"+
    "\12\0\15\43\1\167\10\43\54\0\1\151\4\0\23\43"+
    "\1\170\2\43\52\0\1\152\6\0\21\43\1\171\4\43"+
    "\44\0\1\153\14\0\13\43\1\172\12\43\51\0\1\154"+
    "\7\0\20\43\1\173\5\43\53\0\1\155\5\0\22\43"+
    "\1\174\3\43\53\0\1\156\5\0\22\43\1\175\3\43"+
    "\42\0\1\157\16\0\10\43\1\176\15\43\51\0\1\160"+
    "\7\0\20\43\1\177\5\43\54\0\1\161\4\0\23\43"+
    "\1\200\2\43\51\0\1\162\7\0\20\43\1\201\5\43"+
    "\42\0\1\163\16\0\10\43\1\202\15\43\3\0\3\73"+
    "\2\0\7\73\1\143\3\73\1\203\66\73\41\0\1\204"+
    "\27\0\1\204\44\0\1\205\26\0\1\205\76\0\1\206"+
    "\27\0\1\206\57\0\1\207\1\210\26\0\1\207\1\210"+
    "\36\0\1\211\26\0\1\211\62\0\1\212\26\0\1\212"+
    "\73\0\1\161\27\0\1\161\40\0\1\213\26\0\1\213"+
    "\71\0\1\214\27\0\1\214\52\0\1\215\26\0\1\215"+
    "\53\0\1\216\26\0\1\216\65\0\1\217\27\0\1\217"+
    "\56\0\1\204\14\0\13\43\1\220\12\43\32\0\1\205"+
    "\26\0\1\221\25\43\51\0\1\206\7\0\20\43\1\222"+
    "\5\43\52\0\1\207\1\210\5\0\21\43\1\223\1\224"+
    "\3\43\33\0\1\211\25\0\1\43\1\225\24\43\36\0"+
    "\1\212\22\0\4\43\1\226\21\43\52\0\1\161\6\0"+
    "\21\43\1\200\4\43\34\0\1\213\24\0\2\43\1\227"+
    "\23\43\46\0\1\214\12\0\15\43\1\230\10\43\42\0"+
    "\1\215\16\0\10\43\1\231\15\43\36\0\1\216\22\0"+
    "\4\43\1\232\21\43\44\0\1\217\14\0\13\43\1\233"+
    "\12\43\43\0\1\234\27\0\1\234\66\0\1\162\27\0"+
    "\1\162\45\0\1\235\26\0\1\235\61\0\1\236\27\0"+
    "\1\236\53\0\1\237\26\0\1\237\71\0\1\240\27\0"+
    "\1\240\51\0\1\241\27\0\1\241\46\0\1\242\26\0"+
    "\1\242\64\0\1\234\15\0\12\43\1\243\13\43\53\0"+
    "\1\162\5\0\22\43\1\201\3\43\42\0\1\235\16\0"+
    "\10\43\1\244\15\43\44\0\1\236\14\0\13\43\1\245"+
    "\12\43\41\0\1\237\17\0\7\43\1\246\16\43\53\0"+
    "\1\240\5\0\22\43\1\247\3\43\46\0\1\241\12\0"+
    "\15\43\1\250\10\43\36\0\1\242\22\0\4\43\1\251"+
    "\21\43\46\0\1\252\27\0\1\252\46\0\1\253\26\0"+
    "\1\253\65\0\1\254\27\0\1\254\52\0\1\255\26\0"+
    "\1\255\65\0\1\252\12\0\15\43\1\256\10\43\36\0"+
    "\1\253\22\0\4\43\1\257\21\43\44\0\1\254\14\0"+
    "\13\43\1\260\12\43\40\0\1\255\20\0\6\43\1\261"+
    "\17\43\54\0\1\262\27\0\1\262\50\0\1\263\27\0"+
    "\1\263\64\0\1\262\4\0\23\43\1\264\2\43\46\0"+
    "\1\263\12\0\15\43\1\265\10\43\36\0\1\266\26\0"+
    "\1\266\57\0\1\266\22\0\4\43\1\267\21\43\3\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9230];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\3\1\1\11\2\1\2\11\5\1\2\11"+
    "\17\1\2\11\15\1\1\11\1\1\2\11\1\0\2\11"+
    "\1\0\3\11\1\0\1\1\1\0\3\11\4\0\1\1"+
    "\3\0\1\11\7\0\20\1\2\11\1\0\1\1\7\0"+
    "\2\11\4\0\1\11\1\0\20\1\1\11\1\0\1\11"+
    "\3\0\1\11\3\0\1\11\1\0\14\1\1\11\2\0"+
    "\1\11\2\0\1\11\7\1\1\0\1\11\1\0\1\11"+
    "\4\1\1\0\1\11\2\1\1\11\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[183];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    String cadena = "";
    public LinkedList<Errores> listaErrores = new LinkedList<>();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public scanner(java.io.Reader in) {
      yyline = 1;
    yycolumn = 1;
    listaErrores = new LinkedList<>();
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    return ZZ_CMAP[input];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { listaErrores.add(new Errores("LEXICO", "No se esperaba el caracter: " +yytext(), yyline, yycolumn));
            }
          // fall through
          case 50: break;
          case 2:
            { 
            }
          // fall through
          case 51: break;
          case 3:
            { return new Symbol(sym.NOT, yyline, yycolumn, yytext());
            }
          // fall through
          case 52: break;
          case 4:
            { return new Symbol(sym.MODULO, yyline, yycolumn, yytext());
            }
          // fall through
          case 53: break;
          case 5:
            { return new Symbol(sym.PAR1, yyline, yycolumn, yytext());
            }
          // fall through
          case 54: break;
          case 6:
            { return new Symbol(sym.PAR2, yyline, yycolumn, yytext());
            }
          // fall through
          case 55: break;
          case 7:
            { return new Symbol(sym.MULTIPLICAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 56: break;
          case 8:
            { return new Symbol(sym.MAS, yyline, yycolumn, yytext());
            }
          // fall through
          case 57: break;
          case 9:
            { return new Symbol(sym.MENOS, yyline, yycolumn, yytext());
            }
          // fall through
          case 58: break;
          case 10:
            { return new Symbol(sym.DIVIDIR, yyline, yycolumn, yytext());
            }
          // fall through
          case 59: break;
          case 11:
            { return new Symbol(sym.ENTERO, yyline, yycolumn, yytext());
            }
          // fall through
          case 60: break;
          case 12:
            { return new Symbol(sym.DOSPUNTOS, yyline, yycolumn, yytext());
            }
          // fall through
          case 61: break;
          case 13:
            { return new Symbol(sym.FININSTRUCCION, yyline, yycolumn, yytext());
            }
          // fall through
          case 62: break;
          case 14:
            { return new Symbol(sym.MENORQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 63: break;
          case 15:
            { return new Symbol(sym.IGUAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 64: break;
          case 16:
            { return new Symbol(sym.MAYORQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 65: break;
          case 17:
            { return new Symbol(sym.XOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 66: break;
          case 18:
            { return new Symbol(sym.DEFAULT, yyline, yycolumn, yytext());
            }
          // fall through
          case 67: break;
          case 19:
            { return new Symbol(sym.ID, yyline, yycolumn, yytext());
            }
          // fall through
          case 68: break;
          case 20:
            { return new Symbol(sym.LLAVE1, yyline, yycolumn, yytext());
            }
          // fall through
          case 69: break;
          case 21:
            { return new Symbol(sym.LLAVE2, yyline, yycolumn, yytext());
            }
          // fall through
          case 70: break;
          case 22:
            { return new Symbol(sym.DIFERENCIACION, yyline, yycolumn, yytext());
            }
          // fall through
          case 71: break;
          case 23:
            { String cadena = yytext();
    cadena = cadena.substring(1, cadena.length()-1);//quita las comillas de inicio y las del final: "asdasd" -> asdasd
    cadena = cadena.replace("\\n", "\n").replace("\\t", "\t").replace("\\\"", "\"").replace("\\'", "'").replace("\\\\", "\\");//reemplazando las secuencias de escape con secuencias de escape de java
    return new Symbol(sym.CADENA, yyline, yycolumn, cadena);
            }
          // fall through
          case 72: break;
          case 24:
            { return new Symbol(sym.AND, yyline, yycolumn, yytext());
            }
          // fall through
          case 73: break;
          case 25:
            { return new Symbol(sym.POTENCIA, yyline, yycolumn, yytext());
            }
          // fall through
          case 74: break;
          case 26:
            { return new Symbol(sym.INCREMENTO, yyline, yycolumn, yytext());
            }
          // fall through
          case 75: break;
          case 27:
            { return new Symbol(sym.DECREMENTO, yyline, yycolumn, yytext());
            }
          // fall through
          case 76: break;
          case 28:
            { return new Symbol(sym.MENORIGUALQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 77: break;
          case 29:
            { return new Symbol(sym.IGUALACION, yyline, yycolumn, yytext());
            }
          // fall through
          case 78: break;
          case 30:
            { return new Symbol(sym.MAYORIGUALQUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 79: break;
          case 31:
            { return new Symbol(sym.DO, yyline, yycolumn, yytext());
            }
          // fall through
          case 80: break;
          case 32:
            { return new Symbol(sym.IF, yyline, yycolumn, yytext());
            }
          // fall through
          case 81: break;
          case 33:
            { return new Symbol(sym.OR, yyline, yycolumn, yytext()) ;
            }
          // fall through
          case 82: break;
          case 34:
            { String caracter = yytext();
    caracter = caracter.substring(1, caracter.length()-1);
    return new Symbol(sym.CARACTER, yyline, yycolumn, caracter);
            }
          // fall through
          case 83: break;
          case 35:
            { return new Symbol(sym.DECIMAL, yyline, yycolumn, yytext());
            }
          // fall through
          case 84: break;
          case 36:
            { return new Symbol(sym.FOR, yyline, yycolumn, yytext());
            }
          // fall through
          case 85: break;
          case 37:
            { return new Symbol(sym.INT, yyline, yycolumn, yytext());
            }
          // fall through
          case 86: break;
          case 38:
            { return new Symbol(sym.MUTABILIDAD, yyline, yycolumn, yytext());
            }
          // fall through
          case 87: break;
          case 39:
            { return new Symbol(sym.BOOL, yyline, yycolumn, yytext());
            }
          // fall through
          case 88: break;
          case 40:
            { return new Symbol(sym.CHAR, yyline, yycolumn, yytext());
            }
          // fall through
          case 89: break;
          case 41:
            { return new Symbol(sym.ELSE, yyline, yycolumn, yytext());
            }
          // fall through
          case 90: break;
          case 42:
            { return new Symbol(sym.BOOLEANO, yyline, yycolumn, yytext());
            }
          // fall through
          case 91: break;
          case 43:
            { return new Symbol(sym.BREAK, yyline, yycolumn, yytext());
            }
          // fall through
          case 92: break;
          case 44:
            { return new Symbol(sym.MATCH, yyline, yycolumn, yytext());
            }
          // fall through
          case 93: break;
          case 45:
            { return new Symbol(sym.WHILE, yyline, yycolumn, yytext());
            }
          // fall through
          case 94: break;
          case 46:
            { return new Symbol(sym.DOUBLE, yyline, yycolumn, yytext());
            }
          // fall through
          case 95: break;
          case 47:
            { return new Symbol(sym.STRING, yyline, yycolumn, yytext());
            }
          // fall through
          case 96: break;
          case 48:
            { return new Symbol(sym.IMPRIMIR, yyline, yycolumn, yytext());
            }
          // fall through
          case 97: break;
          case 49:
            { return new Symbol(sym.CONTINUE, yyline, yycolumn, yytext());
            }
          // fall through
          case 98: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
