
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc1_vj24_3363565520917.backend.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR2 = 15;
  public static final int PAR1 = 14;
  public static final int MULTIPLICAR = 12;
  public static final int CONST = 18;
  public static final int CHAR = 22;
  public static final int IGUALACION = 31;
  public static final int IMPRIMIR = 9;
  public static final int ENTERO = 3;
  public static final int XOR = 38;
  public static final int DOUBLE = 20;
  public static final int INT = 19;
  public static final int FOR = 28;
  public static final int MATCH = 26;
  public static final int NOT = 39;
  public static final int AND = 37;
  public static final int MAYORQUE = 46;
  public static final int IGUAL = 42;
  public static final int CARACTER = 5;
  public static final int OR = 36;
  public static final int BOOL = 21;
  public static final int INCREMENTO = 40;
  public static final int UMENOS = 16;
  public static final int IF = 24;
  public static final int FININSTRUCCION = 8;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int MAYORIGUALQUE = 35;
  public static final int DECREMENTO = 41;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 43;
  public static final int MENOS = 11;
  public static final int BREAK = 30;
  public static final int DIFERENCIACION = 33;
  public static final int MENORQUE = 45;
  public static final int POTENCIA = 32;
  public static final int ELSE = 25;
  public static final int DIVIDIR = 13;
  public static final int WHILE = 27;
  public static final int DEFAULT = 44;
  public static final int CORCH2 = 48;
  public static final int CORCH1 = 47;
  public static final int BOOLEANO = 6;
  public static final int MENORIGUALQUE = 34;
  public static final int STRING = 23;
  public static final int VAR = 17;
  public static final int DO = 29;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "BOOLEANO",
  "ID",
  "FININSTRUCCION",
  "IMPRIMIR",
  "MAS",
  "MENOS",
  "MULTIPLICAR",
  "DIVIDIR",
  "PAR1",
  "PAR2",
  "UMENOS",
  "VAR",
  "CONST",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "IF",
  "ELSE",
  "MATCH",
  "WHILE",
  "FOR",
  "DO",
  "BREAK",
  "IGUALACION",
  "POTENCIA",
  "DIFERENCIACION",
  "MENORIGUALQUE",
  "MAYORIGUALQUE",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "INCREMENTO",
  "DECREMENTO",
  "IGUAL",
  "MODULO",
  "DEFAULT",
  "MENORQUE",
  "MAYORQUE",
  "CORCH1",
  "CORCH2"
  };
}

