
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc1_vj24_3363565520917.backend.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 50;
  public static final int PAR2 = 16;
  public static final int PAR1 = 15;
  public static final int MULTIPLICAR = 13;
  public static final int CONST = 19;
  public static final int CHAR = 23;
  public static final int IGUALACION = 32;
  public static final int IMPRIMIR = 10;
  public static final int ENTERO = 3;
  public static final int XOR = 39;
  public static final int DOUBLE = 21;
  public static final int INT = 20;
  public static final int FOR = 29;
  public static final int MATCH = 27;
  public static final int NOT = 40;
  public static final int AND = 38;
  public static final int MAYORQUE = 47;
  public static final int IGUAL = 43;
  public static final int CARACTER = 5;
  public static final int OR = 37;
  public static final int BOOL = 22;
  public static final int MUTABILIDAD = 8;
  public static final int INCREMENTO = 41;
  public static final int UMENOS = 17;
  public static final int IF = 25;
  public static final int FININSTRUCCION = 9;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int DECIMAL = 4;
  public static final int MAYORIGUALQUE = 36;
  public static final int DECREMENTO = 42;
  public static final int error = 1;
  public static final int CADENA = 2;
  public static final int MODULO = 44;
  public static final int MENOS = 12;
  public static final int BREAK = 31;
  public static final int DIFERENCIACION = 34;
  public static final int MENORQUE = 46;
  public static final int POTENCIA = 33;
  public static final int ELSE = 26;
  public static final int DIVIDIR = 14;
  public static final int WHILE = 28;
  public static final int DEFAULT = 45;
  public static final int CORCH2 = 49;
  public static final int CORCH1 = 48;
  public static final int BOOLEANO = 6;
  public static final int MENORIGUALQUE = 35;
  public static final int STRING = 24;
  public static final int VAR = 18;
  public static final int DO = 30;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "BOOLEANO",
  "ID",
  "MUTABILIDAD",
  "FININSTRUCCION",
  "IMPRIMIR",
  "MAS",
  "MENOS",
  "MULTIPLICAR",
  "DIVIDIR",
  "PAR1",
  "PAR2",
  "UMENOS",
  "VAR",
  "CONST",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "IF",
  "ELSE",
  "MATCH",
  "WHILE",
  "FOR",
  "DO",
  "BREAK",
  "IGUALACION",
  "POTENCIA",
  "DIFERENCIACION",
  "MENORIGUALQUE",
  "MAYORIGUALQUE",
  "OR",
  "AND",
  "XOR",
  "NOT",
  "INCREMENTO",
  "DECREMENTO",
  "IGUAL",
  "MODULO",
  "DEFAULT",
  "MENORQUE",
  "MAYORQUE",
  "CORCH1",
  "CORCH2",
  "DOSPUNTOS"
  };
}

